### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by nikneem** [nikneem/azure-functions-jwt-binding#20]
As of now, scopes validation can be done using the binding. This information is missing from the documentation so the documentation must be updated.

Scopes can be passed in comma-separated. Each scope passed in MUST exist in the JWT Token, else validation fails.

Leaving the scopes empty will skip the scope validation

**Comment by pepoflex** [comment]
Please assign me this project, I would love to work on it.

**Comment by nikneem** [comment]
Sure thing, thanks!
