### ISSUE TITLE
Add support for allowed identities

### ISSUE THREAD

**Issue by Jandev** [nikneem/azure-functions-jwt-binding#24]
I'm developing a Function which only a single Logic App (Managed Identity) should be able to invoke.

While I could go through the complete process of creating an App Registration, setting all of this up & configuring the Function with it, and assigning a role (#23)/scope to the Logic App, that's a bit too much of configuration for this specific functionality.

I'd like to do some validation on an allowed the `Subject`.

This is what I've done myself now, but might also be included in the binding.
```csharp
ctor()
{
    AllowedIdentities = Environment.GetEnvironmentVariable("JwtBinding:AllowedIdentities", EnvironmentVariableTarget.Process).Split(',');
}

if(!AllowedIdentities.Any(i => string.Equals(i, auth.Subject, StringComparison.OrdinalIgnoreCase)))
{
	throw new IdentityNotAllowedException(auth.Subject);
}

// With this exception
public class IdentityNotAllowedException : AuthorizationScopesException
{
	public IdentityNotAllowedException(string message, Exception inner = null) : base($"Identity provided in the `oid` claim is not authorizied to contact this endpoint.{Environment.NewLine}{message}", inner)
	{
	}
}
```
Obviously, the allowed identities should be configurable.

**Comment by nikneem** [comment]
If you can make them config-driven:

Given no configuration value for allowed identities is set
When an incoming token is validated
Then no validation on allowed identities is executed

Given a configuration value for allowed identities is set
When an incoming token is validated
  And the value contains no comma
  And this token's subject ID is not equal to the value retrieved from config
Then an IdentityNotAllowedException is thrown

Given a configuration value for allowed identities is set
When an incoming token is validated
  And the value contains one or more commas
  And this token's subject ID is not equal to either one value retrieved from config and split by comma
Then an IdentityNotAllowedException is thrown


Seems like you're pretty close to a PR there ;)
- This may also be a good blue-print solution for #23

**Comment by nikneem** [comment]
I'll assign it to you 👌🏻

**Comment by Jandev** [comment]
If you assign it to me, I'll try to implement this soon.

**Comment by nikneem** [comment]
Roger that!
