### ISSUE TITLE
HelpNeeded: Exception - MS.IdentityModel.Token

### ISSUE THREAD

**Issue by DavidHoffmann** [nikneem/azure-functions-jwt-binding#35]
Hi,

I try to create a demo project with jwtbinding.

I got this code and add a new functions app (.net core 3.1).

Every time I got the exception (see attachment).

![errorMsg](https://user-images.githubusercontent.com/5047272/99420179-379ff980-28fd-11eb-9966-52a5d09f4f73.png)

Can you help me please?

Best regards
  D

avid

**Comment by nikneem** [comment]
Have you tried adding this package to your main assembly?

I also recall this is an error in the functions runtime, you need to add a flag to your project file. I'll get back to you.

**Comment by nikneem** [comment]
Yup, you have to set _FunctionSkipXleanOutput to true. This work-around will fix your issue for now. This is a runtime error of the Functions runtime.

https://github.com/Azure/azure-functions-vs-build-sdk/issues/397

**Comment by DavidHoffmann** [comment]
Thank you for your great support. I managed a working solution.
I'll post some more information. May other developer have similar problems.

I started a new blank solution and add functions project (HTTP-Trigger). After that I add the Nuget package for JwtBinding and update the functions packages to the latest version.

After that I had to manipulate the project file.csproj with an editor. 

## fp.csproj

``` xml
<PropertyGroup>
  <TargetFramework>netcoreapi3.1</TargetFramework>
  <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
</PropertyGroup>
```

## local.settings.json

``` json
    "JwtBinding:Issuer": "https://demo.identityserver.io",
    "JwtBinding:IssuerPattern": "https://demo.identityserver.io",
    "JwtBinding:Audience": "Azure-API",
    "JwtBinding:Roles": "Role1,Role2",
    "JwtBinding:Signature": "asdv234234^&%&^%&^hjsdfb2%%%"
```

## function1.cs

``` csharp
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            [JwtBinding(Roles ="Role1")]AuthorizedModel authorizedModel,
            ILogger log)
```

### Postman - header

I add this header to my postman request

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY3AiOlsiZGF0YTpyZWFkIiwiZGF0YTp3cml0ZSJdLCJyb2xlcyI6WyJSb2xlMSIsIlJvbGUyIl0sInN1YiI6IklkZW50aXR5MSIsIm5iZiI6MTYwNTY5OTA3MCwiZXhwIjoxNjA2MzAzODcwLCJpYXQiOjE2MDU2OTkwNzAsImlzcyI6Imh0dHBzOi8vZGVtby5pZGVudGl0eXNlcnZlci5pbyIsImF1ZCI6IkF6dXJlLUFQSSJ9.qJfHFd72UjTKWw9e2m_fR70SMvC4fyoH5wwcfa-bVh4

**Comment by nikneem** [comment]
Thanks for the feedback, absolutely valuable...
One remark, if the issuer is fixed, like in your example, there is no need to also provide the IssuerPattern. This only applies when (for example) using Azure AD where the issuer is https://login.microsoft.com/{something}.
