### ISSUE TITLE
Add support for configurable header

### ISSUE THREAD

**Issue by gavinwilliams** [nikneem/azure-functions-jwt-binding#42]
Some services (Azure Static Apps  https://github.com/Azure/static-web-apps/issues/34 override the Authorization header value for incoming requests, it would be nice to have this configurable so we can change it to say "X-Authorization" to avoid any conflicts.

https://github.com/nikneem/azure-functions-jwt-binding/blob/58e32891cba08d1619f125ad36e74456d09cf594/src/HexMaster.Functions.JwtBinding/JwtBinding.cs#L63

**Comment by nikneem** [comment]
Closed by change

**Comment by nikneem** [comment]
Thanks for your contribution, this change is not available as of version 1.4.1
